#!/usr/bin/env ruby
require 'shellwords'

hits = []

checks = {
  '\.(rb|haml)$' => ['binding\.pry', 'byebug'],
  '\.js(.jsx)?(.erb)?$' => ['debugger', 'console\.(log|debug|error|info|warn)'],
}

# Find the names of all the filenames that have been (A)dded (C)opied or (M)odified
filenames = `git diff --cached --name-only --diff-filter=ACM`.split("\n")

filenames.each do |filename|
  # Perform special checks for _spec filenames (rspec tests)
  checks.each do |filename_pattern, patterns|
    if filename.match filename_pattern
      patterns.each do |contents_pattern|
        contents_pattern = contents_pattern.shellescape
        results = `git diff --cached  #{filename} | grep "^\+[^+]" | grep #{contents_pattern}`.split("\n").map { |r| r.sub(/^\+[\s\t]*/, '') }
        if $? == 0
          # Add the relevant change with line number to the hits array
          results.each do |r|
            r = r.shellescape
            hits.push "#{filename}:" + `grep -n #{r} #{filename}`.sub(/:\s+/, ' ').chomp
          end
        end
      end
    end
  end
end

if hits.any?
  puts "\e[31m>>> Please remove the following problems from these files before committing\e[0m"
  puts hits.join("\n")
end

exit 1 if hits.any?
