#!/bin/bash

migrate() (
  # if we have a name for the migration AND some `field:type` property
  if [[ 2 -le $# ]]; then
    drails g migration ${1} ${2}
    drake db:migrate

  # if we just have a migration name
  elif [[ 1 -le $# ]]; then
    drails g migration ${1}

  # if we have nothing we just migrate the DB
  elif [[ 0 -le $# ]]; then
    drake db:migrate
  fi
)
