#!/bin/bash

monip () {
  _current_ip=$(wget -q -O - monip.org | grep -m 1 -Po "IP : \K\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}")

  echo $_current_ip | xclip -selection clipboard

  xclip -selection clipboard -o
}
