#!/usr/bin/env bash

PATH="/usr/local/bin:$PATH"
PATH="$HOME/.config/git/bin:$PATH"
PATH="$HOME/.npm-global/bin:$PATH"
PATH="$HOME/bin:$PATH"

MYFILES=`ls -F $HOME/bin | grep "\/"`
for FOLDER in $MYFILES; do
  PATH="$HOME/bin/$FOLDER:$PATH"
  echo "Adding $FOLDER"
done

export PATH

# vim: ft=sh
