#!/bin/sh

set -e

echo "==> Pulling latest dotfiles..."
git pull &> /dev/null
wait $!

echo "==> Updating git submodules..."
git submodule init &> /dev/null
wait $!
git submodule update &> /dev/null
wait $!

echo "==> Done bootstraping!"
