#!/bin/sh

set -e

echo "==> Pulling latest dotfiles..."
git pull &> /dev/null
wait $!

echo "==> Updating git submodules..."
git submodule update --init --recursive &> /dev/null
wait $!

echo "==> Initializing Vim env..."
cd .vim
if [ ! -d "bundle" ]; then
  echo "creating bundle and backup directories"
  mkdir bundle
  mkdir -p tmp/backup tmp/swap tmp/undo
fi

if [ ! -d "bundle/vundle" ]; then
  echo "installing Vundle (https://github.com/gmarik/vundle)."
  git clone https://github.com/gmarik/vundle.git bundle/vundle
fi

vim +BundleInstall +qall &> /dev/null
wait $!
cd -

# Apply settings regarding terminal (aterm or xterm in our case)
xrdb ~/.Xdefaults

echo "==> Done bootstraping!"
