#!/bin/bash

echo "=====> NODE"

# NODEJS {{{1
if [ ! -x "$(command -v node)" ]; then
  curl --fail -LSs https://install-node.now.sh/latest | sh
fi
[ -d $HOME/.npm-global ] || mkdir $HOME/.npm-global
npm config set prefix "$HOME/.npm-global"
# }}}
