#!/bin/bash

set -e

HOME_DIRECTORY=$HOME

usage () {
  echo "Infos -- Usage: ./scripts/install [options]"
  echo "         Options: -d (default: $HOME_DIRECTORY) dotfiles root directory"
  exit 1
}

# Parse the options
while getopts ':d:h' opt
do
  case $opt in
    d)
      echo "Before: $HOME_DIRECTORY"
      HOME_DIRECTORY=$OPTARG
      echo "After: $HOME_DIRECTORY"
      exit 1
      ;;
    h)
      usage
      exit 1
      ;;
    \?)
      echo "Error -- Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
    :)
      echo "Error -- Option -$OPTARG requires an argument."
      usage
      exit 1
      ;;
  esac
done

declare -a list_of_files=(
  ".bundler-exec.sh"
  ".gitconfig"
  ".githelpers"
  ".jshintrc"
  ".tmux.conf"
  ".tmux"
  ".vim"
  ".vimrc"
  ".zlogin"
  ".zlogout"
  ".zprezto"
  ".zpreztorc"
  ".zprofile"
  ".zshenv"
  ".zshrc"
)

case $(uname) in
  'Linux')
    command -v git >/dev/null 2>&1 || {
      echo "==> Installing Git..."
      apt-get install git
    }
    ;;
  'Darwin')
    command -v brew >/dev/null 2>&1 || {
      echo "==> Installing Brew..."
      echo >&2 ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      exit 1
    }
    brew install caskroom/cask/brew-cask Caskroom/cask/tuntap
    brew install git
    ;;
esac

echo "==> Fetching sources..."
git clone git@github.com:AdrienGiboire/dotfiles.git $HOME_DIRECTORY/.dotfiles &> /dev/null
wait $!

cd $HOME_DIRECTORY/.dotfiles

echo "==> Linking dotfiles..."
for file in "${list_of_files[@]}"; do
  if $verbose; then
    echo "====> Linking $file..."
  fi

  ln -s $HOME_DIRECTORY/.dotfiles/$file $HOME_DIRECTORY/$file
done

source ./scripts/os_specifics

echo "==> Bootstrapping..."
$HOME_DIRECTORY/.dotfiles/scripts/bootstrap
