#!/bin/bash

set -o nounset # error when referencing undefined variable

function config { git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@; }
function die { printf '%s\n' "$1" >&2; exit 1; }
function join { local IFS="$1"; shift; echo "$*"; }
function section { printf '\n%s\n' "=== $1"; }
function showme { printf '%s\n' "$1" >&2; }
function cleanup { $HOME/scripts/uninstall; }

trap cleanup ERR

options=$(getopt -o v -l ruby,node -- "$@")
[ $? -eq 0 ] || die "Incorrect options provided"
eval set -- "$options"

with_ruby=false
with_node=false

while true; do
  case "$1" in
    --ruby)
      with_ruby=true
      ;;
    --node)
      with_node=true
      ;;
    *)
      break
      ;;
  esac
  shift
done

# DEPENDENCIES {{{1
utils=(
  apt-transport-https
  arandr
  ca-certificates
  curl
  flatpak
  git
  gnupg-agent
  i3
  jq
  make
  pavucontrol
  scdoc
  silversearcher-ag
  software-properties-common
  tmux
  xclip
)

section "Installing utils {$(join ' ' ${utils[@]})}"
sudo apt-get install -y $(join ' ' ${utils[@]})
# }}}

# FETCH SOURCES {{{1
section "Installing Dotfiles"
git clone --bare git@github.com:AdrienGiboire/dotfiles.git $HOME/.dotfiles

mkdir -p $HOME/.config-backup
config checkout
if [ 0 -le $# ]; then
  echo "Checked out config."
else
  echo "Backing up pre-existing dot files."
  config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} $HOME/.config-backup/{}
fi
config checkout
config config status.showUntrackedFiles no
# }}}

$with_ruby && $HOME/scripts/install-ruby
$with_node && $HOME/scripts/install-node

# FZF {{{1
section "Installing FZF"

{
  git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
  $HOME/.fzf/install
} || {
  showme "Could not install FZF"
}
# }}}

# Rust {{{
# Necessary for some vim plugins like vim-test, and Alacritty
section "Installing Rust and Cargo"
curl https://sh.rustup.rs -sSf | sh
# }}}

# Alacritty {{{
section "Installing Alacritty"
sudo apt install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3

cd /tmp
git clone https://github.com/alacritty/alacritty.git
cd alacritty

rustup override set stable
rustup update stable
cargo build --release

## Terminfo
sudo tic -xe alacritty,alacritty-direct extra/alacritty.info

## Desktop Entry
sudo cp target/release/alacritty /usr/local/bin
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database

# Manual Page
sudo mkdir -p /usr/local/share/man/man1
sudo mkdir -p /usr/local/share/man/man5
scdoc < extra/man/alacritty.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
scdoc < extra/man/alacritty-msg.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
scdoc < extra/man/alacritty.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty.5.gz > /dev/null
scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty-bindings.5.gz > /dev/null

# Shell Completions
mkdir -p ~/.bash_completion
cp extra/completions/alacritty.bash ~/.bash_completion/alacritty

# Theme
curl -LO --output-dir ~/.config/alacritty https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml
# }}}

# VIM {{{1
section "Installing Neovim"

{
  [ ! -d $HOME/Applications ] && mkdir $HOME/Applications
  cd $HOME/Applications
  curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
  chmod u+x nvim.appimage

  section "+ Install Lemonade for clipboard support over SSH"
  curl -fLo /tmp/lemonade.tar.gz https://github.com/lemonade-command/lemonade/releases/latest/download/lemonade_linux_amd64.tar.gz
  tar -xvzf /tmp/lemonade.tar.gz --directory $HOME/bin/
  rm /tmp/lemonade.tar.gz

  section "+ Install python3 provider (mandatory for some plugins)"
  sudo apt install python3-pip
  python3 -m pip install --user --upgrade pynvim

  section "+ Install vim-plug"
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  $HOME/Applications/nvim.appimage --headless +'PlugUpdate --sync' +qa

} || {
  showme "Could not install Neovim"
}
# }}}

# Softwares {{{
section "Installing softwares {$(join ' ' ${softwares[@]})}"

softwares=(
  com.discordapp.Discord
  com.slack.Slack
  com.spotify.Client
  org.telegram.desktop
)

flatpak install -y $(join ' ' ${softwares[@]})
# }}}
