#!/bin/bash

set -e

function join { local IFS="$1"; shift; echo "$*"; }

utils=(
  silversearcher-ag
  autojump
  git
  imagemagick
  libevent-dev
  make
  nodejs
  postgresql
  tmux
  vim
  wget
  zsh
)

echo "==> Installing utils {$(join ' ' ${utils[@]})}"
sudo apt-get install -y $(join ' ' ${utils[@]})
