#!/bin/sh

set -e

function join { local IFS="$1"; shift; echo "$*"; }

utils=(
  silversearcher-ag
  autojump
  git
  imagemagick
  libevent-dev
  make
  nodejs
  postgresql
  tmux
  vim
  wget
)

echo "==> Installing utils {$(join ' ' $utils)}"
aptitude install -y $(join ' ' $utils)
