#!/bin/bash

set -e

mkdir -p $HOME/code

echo "==> Installing ruby..."
brew install ruby-install
ruby-install ruby
brew install chruby

echo "==> Installing gems..."
gem install xcpretty

echo "==> Installing utils..."
utils=(
  ag
  autojump
  caskroom/cask/brew-cask
  Caskroom/cask/tuntap # Has to be before openvpn
  chruby
  flow
  imagemagick
  libevent
  giflib
  git
  ios-sim
  openvpn
  postgresql
  reattach-to-user-namespace
  redis
  ruby-install
  tmux
  vim
  watchman
  wget
)

brew install ${utils[@]}

echo "==> Installing apps..."
apps=(
  alfred
  android-platform-tools
  asepsis
  battle-net
  caffeine
  dash
  dashlane
  divvy
  doubletwist
  evernote
  firefox
  google-chrome
  google-drive
  google-hangouts
  iterm2
  java
  libreoffice
  node
  pg-commander
  postman
  skype
  slack
  steam
  telegram
  tunnelblick
  utorrent
  vagrant
  virtualbox
  vlc
)

brew cask install --appdir="/Applications" ${apps[@]}

brew tap homebrew/services
