#!/bin/sh

set -e

# Detect the platform (similar to $OSTYPE)
export OS=$(uname)
case $OS in
  'Linux')
    OS='Linux'
    source ./scripts/linux_specifics
    ;;
  'FreeBSD')
    OS='FreeBSD'
    ;;
  'WindowsNT')
    OS='Windows'
    ;;
  'Darwin')
    OS='Mac'
    source ./scripts/mac_specifics
    ;;
  'SunOS')
    OS='Solaris'
    ;;
  'AIX') ;;
  *) ;;
esac

