#!/bin/bash

set -e

HOME_DIRECTORY=$HOME

function usage {
  echo "Infos -- Usage: ./scripts/uninstall [options]"
  echo "         Options: -d (default: $HOME_DIRECTORY) dotfiles root directory"
  exit 1
}

# Parse the options
while getopts ':dh' opt
do
  case $opt in
    d)
      HOME_DIRECTORY=$OPTARG
      ;;
    h)
      usage
      exit 1
      ;;
    \?)
      echo "Error -- Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
    :)
      echo "Error -- Option -$OPTARG requires an argument."
      usage
      exit 1
      ;;
    *)
      [ ! -d $HOME_DIRECTORY ] && {
        echo "Could not automatically find '.dotfiles' directory."
        echo "Try again by providing the path to it using the -d option."
        usage
        exit 1
      }
      ;;
  esac
done

for file in "$HOME"/scripts/uninstall-*; do
  [ -r "$file" ] && [ -f "$file" ] && "$file"
done
unset file

# Cleaning Files {{{
declare -a list_of_files=(
  ".bash_profile"
  ".bashrc"
  ".config"
  ".dotfiles"
  ".fzf"
  ".fzf.bash"
  ".gitconfig"
  ".githelpers"
  ".gitignore"
  ".git_template"
  ".jshintrc"
  ".pryrc"
  "bin"
  "README.md"
  "scripts"
)

echo "==> Deleting files..."

for file in "${list_of_files[@]}"; do
  echo "====> Deleting $file..."
  rm -fr $HOME_DIRECTORY/$file
done
# }}}

echo "==> Done Uninstalling."
