#!/bin/bash

set -e

HOME_DIRECTORY=$HOME
VERBOSE=false

usage () {
  echo "Infos -- Usage: ./scripts/uninstall [options]"
  echo "         Options: -d (default: $HOME_DIRECTORY) dotfiles root directory"
  exit 1
}

# Parse the options
while getopts ':d:vh' opt
do
  case $opt in
    d)
      HOME_DIRECTORY=$OPTARG
      ;;
    v)
      VERBOSE=true
      ;;
    h)
      usage
      exit 1
      ;;
    \?)
      echo "Error -- Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
    :)
      echo "Error -- Option -$OPTARG requires an argument."
      usage
      exit 1
      ;;
    *)
      [ ! -d $HOME_DIRECTORY ] && {
        echo "Could not automatically find '.dotfiles' directory."
        echo "Try again by providing the path to it using the -d option."
        usage
        exit 1
      }
      ;;
  esac
done

declare -a list_of_files=(
  ".bundler-exec.sh"
  ".dotfiles"
  ".gitconfig"
  ".githelpers"
  ".jshintrc"
  ".pryrc"
  ".tmux"
  ".tmux.conf"
  ".vim"
  ".vimrc"
  ".zlogin"
  ".zlogout"
  ".zprezto"
  ".zpreztorc"
  ".zprofile"
  ".zshenv"
  ".zshrc"
)

if [ "$#" -gt 0 ] && [ "$1" = "-v" ]; then
  verbose=true
else
  verbose=false
fi

echo "==> Deleting files..."

for file in "${list_of_files[@]}"; do
  if $VERBOSE; then
    echo "====> Deleting $file..."
  fi

  rm -fr $HOME_DIRECTORY/$file
done

echo "==> Done Uninstalling..."
