#!/bin/bash

set -ev

HOME_DIRECTORY=$HOME

usage () {
  echo "Infos -- Usage: ./scripts/update [options]"
  echo "         Options: -d (default: $HOME_DIRECTORY) dotfiles root directory"
  exit 1
}

# Parse the options
while getopts ':d:h' opt
do
  case $opt in
    d)
      echo "Before: $HOME_DIRECTORY"
      HOME_DIRECTORY=$OPTARG
      echo "After: $HOME_DIRECTORY"
      exit 1
      ;;
    h)
      usage
      exit 1
      ;;
    \?)
      echo "Error -- Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
    :)
      echo "Error -- Option -$OPTARG requires an argument."
      usage
      exit 1
      ;;
    *)
      [ ! -d $HOME_DIRECTORY ] && {
        echo "Could not automatically find '.dotfiles' directory."
        echo "Try again by providing the path to it using the -d option."
        usage
        exit 1
      }
      ;;
  esac
done


echo "==> Bootstrapping..."
./.dotfiles/scripts/bootstrap

echo "==> Pulling master for submodules..."
git submodule foreach git pull origin master &> /dev/null
wait $!

echo "==> Done updating!"
git status -s -b
wait $!
