#!/bin/sh

set -e

echo "==> Bootstrapping..."
./scripts/bootstrap

echo "==> Pulling master for submodules..."
git submodule foreach git pull origin master &> /dev/null
wait $!

echo "==> Rebasing oh-my-zsh against upstream..."
cd .oh-my-zsh
git fetch upstream && git rebase upstream/master &> /dev/null
wait $!
cd ~

echo "==> Done updating!"
git status -s -b
wait $!
