#!/bin/bash

set -e

echo "==> Bootstrapping..."
./.dotfiles/scripts/bootstrap

echo "==> Pulling master for submodules..."
git submodule foreach git pull origin master &> /dev/null
wait $!

echo "==> Done updating!"
git status -s -b
wait $!
